[package]
name = "nu_plugin_from_parquet"
version = "0.0.0"
authors = ["Jake Swenson <jake@jakeswenson.com>"]
edition = "2021"
repository = "https://github.com/jakeswenson/nu_plugin_from_parquet"
description = "nu plugin to add parquet support"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nu-plugin = "0.68.0"
# nu-protocol = "0.68.0"
nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.71.1"}
nu-protocol = { path = "../nushell/crates/nu-protocol", version="0.71.1"}
bytes = "1.2.1"
chrono = { version = "0.4.20", features = ["serde"] }
parquet = "22.0.0"
