[package]
name = "nu_plugin_from_parquet"
version = "0.0.2"
authors = ["Jake Swenson <jake@jakeswenson.com>", "Darren Schroeder"]
edition = "2021"
repository = "https://github.com/jakeswenson/nu_plugin_from_parquet"
description = "nu plugin to add parquet support"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nu-plugin = "0.74.0"
# nu-protocol = "0.74.0"
nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.77.2"}
nu-protocol = { path = "../nushell/crates/nu-protocol", version="0.77.2"}
bytes = "1.4.0"
chrono = { version = "0.4.23", features = ["serde"] }
parquet = "36.0.0"

# Would be nice if this worked but it does not
# [patch.crates-io]
# nu-plugin = { git = "https://github.com/nushell/nushell/", branch = "main"}
# nu-protocol = { git = "https://gitnub.com/nushell/nushell/", branch = "main"}
