[package]
authors = ["Darren Schroeder", "Jake Swenson <jake@jakeswenson.com>"]
description = "nu plugin to add parquet support"
edition = "2021"
license = "MIT"
name = "nu_plugin_from_parquet"
repository = "https://github.com/jakeswenson/nu_plugin_from_parquet"
version = "0.0.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nu-plugin = "0.74.0"
# nu-protocol = "0.74.0"
bytes = "1.4.0"
chrono = { version = "0.4.26", features = ["serde"] }
nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.84.1" }
nu-protocol = { path = "../nushell/crates/nu-protocol", version = "0.84.1" }
parquet = "46.0.0"
